name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
  MINT_PATH: mint/lib
  MINT_LINK_PATH: mint/bin

jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        timeout-minutes: 1

      - name: Setup Mint
        uses: irgaly/setup-mint@v1.1.1
        timeout-minutes: 15

      - name: Save Logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: ~/Library/Logs/
